local M = {}

-- stylua: ignore start
M.icons = {
  bracketleft       = '',
  bracketright      = '',
  vim               = '',
  -- vim            = '',
  git               = '',
  -- git            = '',
  github            = '',
  gitlab            = '',
  gitbitbucket      = '',
  hg                = '',
  gitadd            = ' ',
  -- gitadd         = ' ',
  gitmod            = ' ',
  -- gitmod         = '柳',
  gitdel            = ' ',
  -- gitdel         = ' ',
  -- lsp               = '',
  lsp               = '',
  lspdiagerror      = ' ',
  -- lspdiagerror   = ' ',
  lspdiagwarning    = ' ',
  -- lspdiagwarning = ' ',
  lspdiaginfo       = ' ',
  -- lspdiaginfo    = ' ',
  lspdiaghint       = ' ',
  -- lspdiaghint    = ' ',
  dos               = '',
  unix              = '',
  -- unix           = '',
  mac               = '',
  typewriteable     = '',
  -- typewriteable  = '',
  -- typewriteable  = '',
  typereadonly      = '',
  typesize          = '',
  -- typesize       = '',
  typeenc           = '',
  stats             = '⅑',
  -- statsvert      = '⇳',
  statsvert         = '⬍',
  -- statshoriz     = '⇔',
  statshoriz        = '⬌',
  statsspace        = '⯀',
  statstab          = '⯈',
}

M.lsp = {
  Class         = "ﴯ",
  Class_v       = "",
  Color         = "",
  Color_v       = "",
  Constant      = "",
  Constant_v    = "ﲀ",
  Constructor   = "",
  Constructor_v = " ",
  Enum          = "",
  Enum_v        = "練",
  EnumMember    = "",
  Event         = "",
  Field         = "ﰠ",
  Field_v       = "",
  File          = "",
  Folder        = "",
  Function      = "",
  Interface     = "",
  Interface_v   = "ﰮ",
  Keyword       = "",
  Method        = "",
  Method_v      = "",
  Module        = "",
  Module_v      = "",
  Operator      = "",
  Property      = "ﰠ",
  Property_v    = "",
  Reference     = "",
  Reference_v   = "",
  Snippet       = "",
  Snippet_v     = "",
  Struct        = "פּ",
  Struct_v      = " ",
  Text          = "",
  TypeParameter = "",
  Unit          = "塞",
  Value         = "",
  Variable      = "",
  Variable_v    = "",
}

M.borders = {
  a = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
}

-- stylua: ignore end

return M
